version: "3.7"

services:
  autocomplete:
    image: latest
    network_mode: "host"
    command: ./neo cron autocomplete
    container_name: history
    hostname: history
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
