version: "3.7"

services:
    ingress:
        image: killboard:latest
        network_mode: "host"
        restart: on-failure
        command: ./killboard ingress --channel=killhashes
        container_name: ingress
        hostname: ingress
        env_file:
            - ./cmd/killboard/.env
    egress:
        image: killboard:latest
        network_mode: "host"
        restart: on-failure
        command: ./killboard egress --channel=killhashes --date=20080617
        container_name: egress
        hostname: egress
        env_file:
            - ./cmd/killboard/.env
