version: "3.7"

services:
    import:
        image: docker.pkg.github.com/eveisesi/neo/neo:${DOCKER_VERSION}
        network_mode: "host"
        restart: on-failure
        command: ./neo import --gLimit ${PROCESS_LIMIT} --gSleep ${PROCESS_SLEEP}
        container_name: import
        hostname: import
        env_file:
            - .env
        volumes:
            - ./logs:/app/logs
    serve:
        image: docker.pkg.github.com/eveisesi/neo/neo:${DOCKER_VERSION}
        network_mode: "host"
        restart: on-failure
        command: ./neo serve
        container_name: serve
        hostname: serve
        env_file:
            - .env
        volumes:
            - ./logs:/app/logs
    cron:
        image: docker.pkg.github.com/eveisesi/neo/neo:${DOCKER_VERSION}
        network_mode: "host"
        restart: on-failure
        command: ./neo cron
        container_name: cron
        hostname: cron
        env_file:
            - .env
        volumes:
            - ./logs:/app/logs
    listen:
        image: docker.pkg.github.com/eveisesi/neo/neo:${DOCKER_VERSION}
        network_mode: "host"
        restart: on-failure
        command: ./neo listen
        container_name: listen
        hostname: listen
        env_file:
            - .env
        volumes:
            - ./logs:/app/logs
    tracker:
        image: docker.pkg.github.com/eveisesi/neo/neo:${DOCKER_VERSION}
        network_mode: "host"
        restart: on-failure
        command: ./neo tracking
        container_name: tracker
        hostname: tracker
        env_file:
            - .env
        volumes:
            - ./logs:/app/logs
    notifier:
        image: docker.pkg.github.com/eveisesi/neo/neo:${DOCKER_VERSION}
        network_mode: "host"
        restart: on-failure
        command: ./neo notifications
        container_name: notifier
        hostname: notifier
        env_file:
            - .env
        volumes:
            - ./logs:/app/logs
    updater:
        image: docker.pkg.github.com/eveisesi/neo/neo:${DOCKER_VERSION}
        network_mode: "host"
        restart: on-failure
        command: ./neo updater
        container_name: updater
        hostname: updater
        env_file:
            - .env
        volumes:
            - ./logs:/app/logs
    backup:
        image: docker.pkg.github.com/eveisesi/neo/neo:${DOCKER_VERSION}
        network_mode: "host"
        restart: on-failure
        command: ./neo backup
        container_name: backup
        hostname: backup
        env_file:
            - .env
        volumes:
            - ./logs:/app/logs
