version: "3.7"

services:
    import:
        image: docker.pkg.github.com/eveisesi/neo/neo:${DOCKER_VERSION}
        network_mode: "host"
        restart: on-failure
        command: ./neo import --gLimit ${PROCESS_LIMIT} --gSleep ${PROCESS_SLEEP}
        container_name: import
        hostname: import
        env_file:
            - .env
        volumes:
            - ./logs:/app/logs
    serve:
        image: docker.pkg.github.com/eveisesi/neo/neo:${DOCKER_VERSION}
        network_mode: "host"
        restart: on-failure
        command: ./neo serve
        container_name: serve
        hostname: serve
        env_file:
            - .env
        volumes:
            - ./logs:/app/logs
    cron:
        image: docker.pkg.github.com/eveisesi/neo/neo:${DOCKER_VERSION}
        network_mode: "host"
        restart: on-failure
        command: ./neo cron
        container_name: cron
        hostname: cron
        env_file:
            - .env
        volumes:
            - ./logs:/app/logs
    listen:
        image: docker.pkg.github.com/eveisesi/neo/neo:${DOCKER_VERSION}
        network_mode: "host"
        restart: on-failure
        command: ./neo listen
        container_name: listen
        hostname: listen
        env_file:
            - .env
        volumes:
            - ./logs:/app/logs
    tracker:
        image: docker.pkg.github.com/eveisesi/neo/neo:${DOCKER_VERSION}
        network_mode: "host"
        restart: on-failure
        command: ./neo tracking
        container_name: tracker
        hostname: tracker
        env_file:
            - .env
        volumes:
            - ./logs:/app/logs
    ui:
        image: docker.pkg.github.com/eveisesi/neo-ui/ui:0.1.2
        restart: always
        container_name: ui
        hostname: ui
        ports:
            - "5000:80"
